version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_container'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongoDB/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongoDB/mongo-volume:/data/db
    ports:
      - '27017:27017'
  nats:
    image: nats
    container_name: 'nats_container'
    ports:
      - "4222:4222"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    restart: always
    links:
      - database
      - nats
  incidents_server:
    build:
      context: ./incidents-server
      dockerfile: Dockerfile
    volumes:
      - ./incidents-server:/incidents-server
      - /incidents-server/node_modules
    env_file: .env
    ports:
      - "${INCIDENTS_PORT}:${INCIDENTS_PORT}"
    restart: always
    links:
      - nats
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    ports:
      - "3010:3010"
    restart: always
    links:
      - server

